In [1]:
import numpy as np


In [21]:
j=[4,6,2,8,9,1]
j

[4, 6, 2, 8, 9, 1]

In [26]:
np.array(j)

array([4, 6, 2, 8, 9, 1])

In [27]:
tuple(j)

(4, 6, 2, 8, 9, 1)

In [28]:
d=np.array(j)

In [29]:
d

array([4, 6, 2, 8, 9, 1])

In [30]:
d.ndim

1

In [31]:
d.shape

(6,)

In [32]:
w=d.reshape(2,3)
w

array([[4, 6, 2],
       [8, 9, 1]])

In [11]:
d.size

5

In [12]:
import numpy as np


In [13]:
s=[[1,2,3,4],[5,6,7,8],[9,0,11,12],[13,14,15,16],[17,18,19,20]]
s


[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 0, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20]]

In [14]:
arr1=np.array(s)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
arr1.shape

(5, 4)

In [16]:
arr1.size

20

In [17]:
arr1.ndim

2

In [20]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [33]:
z=arr1.reshape(20,1)
z

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 0],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [34]:
range(5, 20)

range(5, 20)

In [35]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [36]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [37]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [38]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [39]:
range(5,50,5)

range(5, 50, 5)

In [40]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [41]:
j=[10,20,30,40,50,60,70,80,90]
j

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [43]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])
        print(x)
        print(y)

[10]
[20]
[10, 30]
[20, 40]
[10, 30, 50]
[20, 40, 60]
[10, 30, 50, 70]
[20, 40, 60, 80]
