In [1]:
import numpy as np


In [8]:
a=np.random.randint(20,60,15)

In [9]:
a

array([53, 56, 48, 33, 24, 37, 57, 46, 21, 57, 38, 37, 36, 25, 49])

In [17]:
a[2]

48

In [10]:
a.ndim

1

In [11]:
a[10]

38

In [12]:
a[-2:-9:-1]

array([25, 36, 37, 38, 57, 21, 46])

In [19]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [20]:
b[2]

array([30, 41, 26, 21, 28, 29, 17, 38])

In [21]:
b[:,7]  #column--vertical

array([23, 18, 38, 35, 35, 47, 39])

In [22]:
b[3,1] #3rd row and 1st column

47

In [23]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])

In [24]:
b[1:5,1:5]

array([[29, 48, 25, 47],
       [41, 26, 21, 28],
       [47, 16, 15, 48],
       [30, 25, 34, 42]])

In [26]:
#array [row-start : row-end : row-step , col-start : col-end : col-step]


In [28]:
b[3:7,2:7]

array([[16, 15, 48, 22, 44],
       [25, 34, 42, 16, 39],
       [21, 45, 37, 48, 23],
       [37, 17, 45, 24, 44]])

In [29]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [30]:
b[1:7,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [42]:
b[2:5:2,1:8:3]                                                                                    #41,28,38,30,42,35

array([[41, 28, 38],
       [30, 42, 35]])

In [44]:
b[b>30]

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 6, 6, 6, 6, 6], dtype=int64),
 array([0, 3, 4, 5, 6, 0, 2, 4, 5, 6, 1, 7, 0, 1, 4, 6, 7, 3, 4, 6, 7, 0,
        1, 3, 4, 5, 7, 1, 2, 4, 6, 7], dtype=int64))