In [1]:
stud_2nd=[18,19,20,20,20,19,18,18,18,20,20]

In [2]:
import numpy as np
np.random.randint(18,21,(300))

array([20, 19, 19, 18, 19, 19, 20, 18, 20, 18, 18, 18, 19, 20, 19, 18, 19,
       19, 19, 20, 18, 20, 19, 20, 18, 18, 18, 19, 18, 19, 19, 19, 19, 18,
       19, 19, 19, 18, 20, 19, 20, 18, 20, 19, 19, 20, 19, 20, 19, 19, 18,
       20, 20, 20, 18, 18, 20, 18, 20, 18, 18, 19, 18, 19, 20, 20, 20, 20,
       18, 19, 20, 18, 19, 18, 18, 20, 19, 18, 18, 18, 20, 18, 19, 18, 20,
       18, 20, 19, 18, 18, 18, 18, 19, 20, 20, 18, 20, 18, 19, 19, 18, 19,
       19, 18, 20, 19, 19, 18, 20, 19, 19, 20, 18, 20, 20, 20, 19, 20, 19,
       20, 20, 19, 18, 20, 18, 18, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18,
       20, 20, 20, 20, 20, 20, 20, 20, 18, 20, 18, 20, 19, 19, 19, 19, 20,
       18, 18, 18, 20, 19, 18, 20, 20, 20, 19, 20, 18, 18, 20, 18, 20, 20,
       19, 18, 20, 18, 19, 20, 18, 18, 19, 20, 20, 19, 20, 19, 20, 20, 18,
       19, 18, 18, 18, 20, 20, 20, 18, 20, 18, 18, 20, 18, 19, 19, 18, 18,
       18, 19, 19, 20, 18, 18, 20, 20, 18, 20, 19, 18, 18, 20, 18, 20, 20,
       20, 18, 20, 19, 19

In [4]:
import numpy as np
tenth_std=np.random.randint(15,18,(1000))
tenth_std+0.3


array([16.3, 16.3, 16.3, 15.3, 17.3, 15.3, 15.3, 17.3, 16.3, 15.3, 15.3,
       17.3, 15.3, 15.3, 15.3, 16.3, 17.3, 16.3, 16.3, 16.3, 15.3, 17.3,
       15.3, 15.3, 17.3, 16.3, 15.3, 15.3, 16.3, 17.3, 15.3, 15.3, 15.3,
       17.3, 17.3, 16.3, 17.3, 15.3, 16.3, 16.3, 17.3, 17.3, 16.3, 15.3,
       15.3, 16.3, 16.3, 16.3, 16.3, 16.3, 15.3, 16.3, 15.3, 16.3, 17.3,
       16.3, 17.3, 16.3, 16.3, 15.3, 17.3, 15.3, 15.3, 17.3, 15.3, 16.3,
       16.3, 17.3, 16.3, 17.3, 15.3, 16.3, 17.3, 16.3, 15.3, 17.3, 15.3,
       17.3, 17.3, 16.3, 16.3, 16.3, 15.3, 15.3, 16.3, 17.3, 16.3, 15.3,
       17.3, 15.3, 17.3, 15.3, 16.3, 17.3, 17.3, 16.3, 15.3, 16.3, 15.3,
       16.3, 15.3, 17.3, 16.3, 15.3, 17.3, 17.3, 16.3, 17.3, 17.3, 15.3,
       15.3, 15.3, 17.3, 17.3, 17.3, 16.3, 16.3, 15.3, 17.3, 15.3, 17.3,
       15.3, 16.3, 16.3, 17.3, 17.3, 15.3, 16.3, 15.3, 17.3, 15.3, 16.3,
       17.3, 15.3, 15.3, 15.3, 15.3, 15.3, 15.3, 17.3, 16.3, 16.3, 16.3,
       16.3, 17.3, 15.3, 16.3, 15.3, 17.3, 16.3, 16

In [5]:
np.random.randint(120,200,(500))

array([148, 142, 165, 120, 165, 184, 159, 181, 188, 139, 189, 126, 136,
       145, 148, 159, 169, 135, 145, 150, 142, 171, 135, 133, 134, 158,
       161, 123, 181, 160, 175, 129, 181, 160, 156, 160, 180, 152, 153,
       134, 198, 126, 152, 130, 165, 126, 154, 171, 147, 128, 180, 197,
       173, 132, 191, 159, 190, 164, 156, 197, 160, 177, 165, 188, 121,
       184, 149, 196, 157, 179, 123, 141, 167, 134, 148, 135, 174, 126,
       132, 140, 124, 164, 157, 141, 151, 149, 157, 147, 193, 153, 134,
       192, 169, 167, 189, 145, 135, 132, 187, 165, 190, 144, 190, 178,
       129, 147, 195, 162, 171, 197, 161, 196, 193, 137, 165, 160, 140,
       122, 186, 137, 137, 150, 145, 120, 163, 121, 156, 146, 144, 186,
       155, 148, 129, 152, 197, 146, 144, 121, 164, 123, 149, 149, 129,
       135, 146, 132, 159, 130, 163, 184, 192, 171, 186, 167, 196, 141,
       169, 127, 123, 123, 127, 163, 134, 178, 133, 136, 135, 158, 122,
       144, 152, 146, 181, 148, 140, 178, 139, 149, 149, 126, 14

In [6]:
import numpy as np

In [19]:
np.random.seed(234)
arr=np.random.randint(20,99,(6,7))

In [20]:
arr

array([[92, 51, 88, 77, 53, 23, 74],
       [83, 87, 54, 74, 28, 59, 91],
       [52, 79, 84, 46, 91, 43, 23],
       [35, 65, 65, 23, 97, 93, 71],
       [39, 40, 43, 38, 27, 35, 61],
       [23, 93, 60, 93, 75, 43, 98]])

In [21]:
arr.size


42

In [22]:
m=[5,20,10,6,8]
m

[5, 20, 10, 6, 8]

In [26]:
m=[5,20,10,6,8]
squared_numbers = [x**2 for x in m]
print("Squared list:", squared_numbers)


Squared list: [25, 400, 100, 36, 64]


In [35]:
b=(3,6,7,8,9)
b

(3, 6, 7, 8, 9)

In [36]:
b=tuple(x+5 for x in b)
b


(8, 11, 12, 13, 14)

In [38]:
k=[55,25,85,75,35,45,95]
k

[55, 25, 85, 75, 35, 45, 95]

In [40]:
k=[x for x in k if x > 50]
k


[55, 85, 75, 95]

In [45]:
np.random.seed(5)
arr=np.random.randint(20,90,10)

In [46]:
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [47]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [52]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])

In [53]:
arr-20

array([61, 16,  8, 62, 27, 30,  7, 15, 53, 27])

In [54]:
arr[arr==40]

array([], dtype=int32)

In [55]:
arr[arr==50]

array([50])